# Generated by Django 4.2.6 on 2024-04-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AllDataHub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasedetails',
            old_name='disease_prevention',
            new_name='disease_precaution',
        ),
    ]
