# Generated by Django 4.2.6 on 2024-04-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllDataHub', '0002_rename_disease_prevention_diseasedetails_disease_precaution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasedetails',
            name='disease_treatment',
        ),
        migrations.AlterField(
            model_name='diseasedetails',
            name='disease_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
