# Generated by Django 4.2.6 on 2024-04-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastrecords',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
